version: "3"

services:

  plone5:
    image: plone/plone-backend:5
    ports:
    - "8081:8080"
    volumes:
    - ./:/app/src/eea.api.controlpanel
    environment:
      ZOPE_FORM_MEMORY_LIMIT: '250MB'
      SECURITY_POLICY_IMPLEMENTATION: "C"
      VERBOSE_SECURITY: "off"
      DEFAULT_ZPUBLISHER_ENCODING: "utf-8"
      DEBUG_MODE: "off"
      ZODB_CACHE_SIZE: "50000"
      SITE: "Plone"
      PROFILES: "eea.api.controlpanel:default"
      DEVELOP: "/app/src/eea.api.controlpanel"
    tty: true
    stdin_open: true
    command: cat
    # docker-compose exec plone5 bash
    # gosu plone /app/bin/runwsgi -v etc/zope.ini config_file=zope.conf

  plone6:
    image: plone/plone-backend:6
    ports:
    - "8080:8080"
    volumes:
    - ./:/app/src/eea.api.controlpanel
    environment:
      ZOPE_FORM_MEMORY_LIMIT: '250MB'
      SECURITY_POLICY_IMPLEMENTATION: "C"
      VERBOSE_SECURITY: "off"
      DEFAULT_ZPUBLISHER_ENCODING: "utf-8"
      DEBUG_MODE: "off"
      ZODB_CACHE_SIZE: "50000"
      SITE: "Plone"
      PROFILES: "eea.api.controlpanel:default"
      DEVELOP: "/app/src/eea.api.controlpanel"
    tty: true
    stdin_open: true
    command: cat
    # docker-compose exec plone6 bash
    # gosu plone /app/bin/runwsgi -v etc/zope.ini config_file=zope.conf
